# Generated by Django 6.0.3 on 2026-05-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='penalty_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('late', 'Kech kelish'), ('absent', 'Darsga kelmadi'), ('behavior', 'Xulq-atvor'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_penalties', to='register_withvue.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='register_withvue.student')),
            ],
        ),
    ]
