# Generated by Django 6.0.5 on 2026-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0002_remove_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('odd', 'Du-Chor-Juma'), ('even', 'Se-Pay-Shan')], default='odd', max_length=10),
        ),
    ]
